# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: - task: aquasecScanner@4
  inputs:
    image: 'ubuntu:latest'
    scanType: 'local'
    register: true
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '4.2.0'
    connection: 'capitalandtest'
    caCertificates: true
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
